CREATE TABLE IF NOT EXISTS MOVIE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS PERSON (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;

INSERT INTO MOVIE(TITLE, DESCRIPTION) VALUES('THE LORD OF THE RINGS | TWO TOWERS', 'good');
INSERT INTO MOVIE(TITLE, DESCRIPTION) VALUES('THE LORD OF THE RINGS | RETURN OF THE KING', 'good');

INSERT INTO PERSON(NAME) VALUES('Alex');